version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile # Archivo Dockerfile del backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_container:27017/historial_medico
    depends_on:
      - mongo_container

  mongo_container:
    image: mongo:8.0.1
    container_name: mongo_container
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
